"""
joint_axis_explorations.py

This script loads motion capture (marker) and IMU-based (Mag Adapt) trial data
for multiple subjects to perform a comparative analysis of joint kinematics.

For each joint (knee, ankle), it:
1.  Estimates the joint center offset vector using both marker-based and IMU-based methods and compares them.
2.  For knees, it estimates the hinge joint axis from both data sources and compares them.
3.  For ankles, it estimates the two primary axes from the IMU orientation history and compares the primary axis to the one derived from marker data.
"""

import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import numpy as np
from src.toolchest.PlateTrial import PlateTrial
from src.toolchest.WorldTrace import WorldTrace
from generate_method_orientation_sto_files import JOINT_SEGMENT_DICT
import matplotlib.pyplot as plt

COMP_METHOD = 'Mag Adapt'  # The IMU-based orientation method to compare against Marker data

def find_plate_by_name(plate_trials, name_part):
    """Helper function to find a PlateTrial in a list by a substring of its name."""
    return next((p for p in plate_trials if name_part in p.name), None)

def main():
    """
    Main function to run the joint axis and offset exploration analysis.
    """
    # Iterate over all available subjects
    for subject_num in ['01']:#, '02', '03', '04', '05', '06', '07', '08', '09', '10', '11']:
        subject_id = f"Subject{subject_num}"
        print(f"\n{'='*25} Processing {subject_id} {'='*25}")
        trial_type = 'complexTasks'  # Could also loop over different trial types if needed

        # --- 1. Load Marker (Ground Truth) and Mag Adapt (IMU) Data ---
        try:
            # Construct the absolute path to the subject's data folder
            data_folder_path = os.path.abspath(os.path.join("data", subject_id, trial_type))

            # Load PlateTrials from the base folder, which contains marker data (.trc) and raw IMU data
            print(f"Loading Marker data from: {data_folder_path}")
            plate_trials_marker = PlateTrial.load_trial_from_folder(data_folder_path)
            
            # Extract the raw IMU traces, which are shared for all analyses
            imu_traces = {trial.name: trial.imu_trace.copy() for trial in plate_trials_marker}

            # Load world traces generated by the 'Mag Adapt' orientation algorithm from .sto file
            sto_file_path = os.path.join(data_folder_path, f"{trial_type}_orientations_{COMP_METHOD.lower().replace(' ', '_')}.sto")
            print(f"Loading {COMP_METHOD} data from: {sto_file_path}")
            world_traces_alt = WorldTrace.load_from_sto_file(sto_file_path)

            # Generate PlateTrials for the Mag Adapt method by combining raw IMU data with the algorithm's orientations
            plate_trials_alt = PlateTrial.generate_plate_from_traces(
                imu_traces,
                world_traces_alt,
                align_plate_trials=False
            )
        except Exception as e:
            print(f"Could not load data for {subject_id}, {trial_type}. Error: {e}. Skipping.")
            continue
            
        # --- 2. Synchronize Trial Lengths for a Fair Comparison ---
        min_len_marker = min((len(t) for t in plate_trials_marker), default=0)
        min_len_mag = min((len(t) for t in plate_trials_alt), default=0)
        min_length = min(min_len_marker, min_len_mag)
        
        if min_length < 100: # Ensure there is enough data to process
            print(f"Insufficient overlapping data for {subject_id}. Skipping.")
            continue

        plate_trials_marker = [trial[:min_length] for trial in plate_trials_marker]
        plate_trials_alt = [trial[:min_length] for trial in plate_trials_alt]

        # --- 3. Process Each Joint Defined in the Dictionary ---
        for joint, (parent_name, child_name) in JOINT_SEGMENT_DICT.items():
            print(f"\n--- Analyzing Joint: {joint.upper()} ---")
            
            # Find the specific parent and child PlateTrial objects for both methods
            parent_marker = find_plate_by_name(plate_trials_marker, parent_name)
            child_marker = find_plate_by_name(plate_trials_marker, child_name)
            parent_alt = find_plate_by_name(plate_trials_alt, parent_name)
            child_alt = find_plate_by_name(plate_trials_alt, child_name)

            if not all([parent_marker, child_marker, parent_alt, child_alt]):
                print(f"Missing plate data for joint {joint}. Skipping joint analysis.")
                continue

            # # --- 4. Joint Offset Vector Estimation and Comparison ---
            # print("\n* Joint Offset Vector Comparison *")

            # r_c_p = np.array(parent_marker.world_trace.positions) - np.array(child_marker.world_trace.positions)

            # # Method 1: Marker-based offset from WorldTrace kinematics
            # marker_offset_parent, marker_offset_child, _ = parent_marker.world_trace.get_joint_center(child_marker.world_trace)
            # marker_offset_error = np.linalg.norm([R_wp @ marker_offset_parent - R_wc @ marker_offset_child + delta for R_wp, R_wc, delta in zip(parent_marker.world_trace.rotations, child_marker.world_trace.rotations, r_c_p)], axis=1)
            
            # # Method 2: IMU-based offset from raw accelerometer/gyroscope data
            # imu_offset_result = parent_marker.imu_trace.find_spheroidal_joint_offset(child_marker.imu_trace, -marker_offset_parent, -marker_offset_child)
            # imu_offset_parent = imu_offset_result['offset_self']
            # imu_offset_child = imu_offset_result['offset_other']
            # imu_offset_error = np.linalg.norm([R_wp @ imu_offset_parent - R_wc @ imu_offset_child - delta for R_wp, R_wc, delta in zip(parent_marker.world_trace.rotations, child_marker.world_trace.rotations, r_c_p)], axis=1)

            # # Report results
            # print(f"  Marker Parent ({parent_name}) Offset: {np.round(marker_offset_parent, 4)}")
            # print(f"  IMU Parent ({parent_name}) Offset:    {np.round(imu_offset_parent, 4)}")
            # parent_diff = np.linalg.norm(marker_offset_parent - imu_offset_parent)
            # print(f"  > Norm of Difference (Parent): {parent_diff:.4f} m\n")

            # print(f"  Marker Child ({child_name}) Offset:  {np.round(marker_offset_child, 4)}")
            # print(f"  IMU Child ({child_name}) Offset:     {np.round(imu_offset_child, 4)}")
            # child_diff = np.linalg.norm(marker_offset_child - imu_offset_child)
            # print(f"  > Norm of Difference (Child):  {child_diff:.4f} m")

            # print(f"  Marker Offset mean error: {np.mean(marker_offset_error):.4f} m, STD: {np.std(marker_offset_error):.4f} m")
            # print(f"  IMU Offset mean error: {np.mean(imu_offset_error):.4f} m, STD: {np.std(imu_offset_error):.4f} m")

            # plt.figure(figsize=(10, 4))
            # plt.plot(marker_offset_error, label='Marker Offset Error', color='blue')
            # plt.plot(imu_offset_error, label='IMU Offset Error', color='orange')
            # plt.title(f'Joint Offset Error over Time for {joint.capitalize()} Joint')
            # plt.xlabel('Frame')
            # plt.ylabel('Offset Error (m)')
            # plt.legend()
            # plt.grid()
            # plt.show()

            # # --- 5. Knee-Specific: Hinge Joint Axis Estimation ---
            # if 'knee' in joint.lower():
            #     print("\n* Hinge Joint Axis Comparison (Knee) *")
            #     # Method 1: Marker-based axis via principal component analysis of relative rotations
            #     marker_parent_axis, marker_child_axis = parent_marker.world_trace.get_primary_joint_axis(child_marker.world_trace)
            #     marker_hinge_axis_error = np.linalg.norm([R_wp @ marker_parent_axis - R_wc @ marker_child_axis for R_wp, R_wc in zip(parent_marker.world_trace.rotations, child_marker.world_trace.rotations)], axis=1)
                
            #     # Method 2: IMU-based axis from raw gyroscope data
            #     results_dict = parent_marker.imu_trace.find_hinge_joint_axis(child_marker.imu_trace, marker_parent_axis, marker_child_axis)
            #     imu_axis_parent = results_dict['axis_self']
            #     imu_axis_child = results_dict['axis_other']
            #     imu_hinge_axis_error = np.linalg.norm([R_wp @ imu_axis_parent - R_wc @ imu_axis_child for R_wp, R_wc in zip(parent_marker.world_trace.rotations, child_marker.world_trace.rotations)], axis=1)

            #     # Report results
            #     plt.figure(figsize=(10, 4))
            #     plt.plot(marker_hinge_axis_error, label='Marker Hinge Axis Error', color='blue')
            #     plt.plot(imu_hinge_axis_error, label='IMU Hinge Axis Error', color='orange')
            #     plt.title(f'Hinge Joint Axis Error over Time for {joint.capitalize()} Joint')
            #     plt.xlabel('Frame')
            #     plt.ylabel('Hinge Axis Error (m)')
            #     plt.legend()
            #     plt.grid()
            #     plt.show()
                
            # --- 6. Knee-Specific: 2-DOF Joint Axes Estimation ---
            if 'knee' in joint.lower():
                print("\n* 2-DOF Joint Axes Comparison (Knee) *")

                # Method 2: Marker-based axes via PCA
                marker_axes = parent_marker.find_biaxial_joint_axes(child_marker, verbose=True)
                marker_axis1 = marker_axes['axis_parent_local']
                marker_axis2 = marker_axes['axis_child_local']
                marker_carrying_angle = 0 # marker_axes.get('carrying_angle_rad', 0) * 180 / np.pi
                marker_j1_world = np.array([R @ marker_axis1 for R in parent_marker.world_trace.rotations])
                marker_j2_world = np.array([R @ marker_axis2 for R in child_marker.world_trace.rotations])
                marker_j3_world = np.cross(marker_j1_world, marker_j2_world)
                marker_j3_world_norm = np.linalg.norm(marker_j3_world, axis=1)
                carrying_angle_errors = np.arcsin(np.clip(marker_j3_world_norm, -1.0, 1.0)) * 180 / np.pi

                # Method 1: IMU-based axes using a 2-DOF model on orientation history
                imu_2dof_result = parent_alt.find_biaxial_joint_axes(child_alt, verbose=True)
                imu_axis1 = imu_2dof_result['axis_parent_local']
                imu_axis2 = imu_2dof_result['axis_child_local']
                carrying_angle = 0 # imu_2dof_result.get('carrying_angle_rad', 0) * 180 / np.pi
                imu_j1_world = np.array([R @ imu_axis1 for R in parent_alt.world_trace.rotations])
                imu_j2_world = np.array([R @ imu_axis2 for R in child_alt.world_trace.rotations])
                imu_j3_world = np.cross(imu_j1_world, imu_j2_world)
                imu_j3_world_norm = np.linalg.norm(imu_j3_world, axis=1)
                imu_carrying_angle_errors = np.arcsin(np.clip(imu_j3_world_norm, -1.0, 1.0)) * 180 / np.pi

                random_axis_1 = np.random.randn(3)
                random_axis_1 /= np.linalg.norm(random_axis_1)
                random_axis_1 = np.array([R @ random_axis_1 for R in parent_marker.world_trace.rotations])
                random_axis_2 = np.random.randn(3)
                random_axis_2 /= np.linalg.norm(random_axis_2)
                random_axis_2 = np.array([R @ random_axis_2 for R in child_marker.world_trace.rotations])
                carrying_angle_random = np.cross(random_axis_1, random_axis_2)
                carrying_angle_random_norm = np.linalg.norm(carrying_angle_random, axis=1)
                carrying_angle_random_errors = np.arcsin(np.clip(carrying_angle_random_norm, -1.0, 1.0)) * 180 / np.pi

                # Report results
                print(f"  Marker Axes: {np.round(marker_axis1, 4)} and {np.round(marker_axis2, 4)}")
                print(f"  > Mean Carrying Angle Error (Marker): {np.mean(carrying_angle_errors):.2f} deg, STD: {np.std(carrying_angle_errors):.2f} deg")
                print(f"  IMU Axes:    {np.round(imu_axis1, 4)} and {np.round(imu_axis2, 4)}")
                print(f"  > Mean Carrying Angle Error (IMU): {np.mean(imu_carrying_angle_errors):.2f} deg, STD: {np.std(imu_carrying_angle_errors):.2f} deg")
                angle_axis1 = np.arccos(np.clip(np.dot(marker_axis1, imu_axis1), -1.0, 1.0)) * 180 / np.pi
                angle_axis2 = np.arccos(np.clip(np.dot(marker_axis2, imu_axis2), -1.0, 1.0)) * 180 / np.pi
                print(f"  > Angle between primary axes: {angle_axis1:.2f} degrees")
                print(f"  > Angle between secondary axes: {angle_axis2:.2f} degrees")
                print(f"  > Carrying Angle: Marker = {marker_carrying_angle:.2f} deg, IMU = {carrying_angle:.2f} deg") 

                plt.figure(figsize=(10, 4))
                plt.plot(carrying_angle_errors, label='Marker Carrying Angle Error', color='blue')
                plt.plot(imu_carrying_angle_errors, label='IMU Carrying Angle Error', color='orange')
                plt.plot(carrying_angle_random_errors, label='Random Carrying Angle Error', color='green', linestyle='--')
                plt.title(f'Carrying Angle Error over Time for {joint.capitalize()} Joint')
                plt.xlabel('Frame')
                plt.ylabel('Carrying Angle Error (degrees)')
                plt.legend()
                plt.grid()
                plt.show()


if __name__ == "__main__":
    main()